language: go
env:
  global: # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
  - secure: 1FZPRFPXev9+iXg9VZHt7OLLrPTSaPZmoRZ+yg6L6JPy56+l4rPC4PNb/OAmAN2Q2WEWIsZpEFV2a0GW/eOtJBHBBmwr/NcBzJGCxl9snB+m3e0M1lfAPei4BP00tGuJ/qC3AeUWETtKjB+1EzXb4oQcIClpWgLRs8yXtQa2Ps+w7JLqorXnpz3rZhqmrbrUecrwkSDmq+crLmCM5GVo4s8JtqB1XZOmSZ/jyyWOVkM9W8DN/mX2O6vk5KQ6KbUxT3VCStkv1SRGdaNvntdB7+A4X1NNpZEuI/ODIrXB2KE8KFtAq994lx1OPhwo58zLm4CsflZisfqb0UZbIDVM0gEWrrcwrAyIFdF/bUziMrDBfu5u/DAg2uXajN+0GWvVoZORpN24GzZ8aKy0xJ2yJnZQF9Bkc+e5B6n9bwNDJ0Crz7o/OhkeCgmTCORpdyGk+OLZoB1KS72myOdZzi1OCyXeYHl3v5O1uISS2Ciel1UWCqCXXoi+OpxAuYvLw6VkcdGUDMFcMc1t8w2kgYcEJ5WT1MVwy3VxaJ8sXF42jAWzcGQjmyWAUOKih1RfO3TaRHMRSXEw6CvZuLMS8pUjIAiBDfq917cbW+7huWlwlFW35knWOi2LnscPe4b3+vh8pgqN+fnP2zjHrtOr2Pi/0xMjwDJ3m33eJgh11j7PoKk=
  - secure: p7A6QQ7YH6LobzK/v5yUe15VVqM/rQ0p9xNx4/gn6oEetg2GGb1F56CwUSSWMhBXnguSrktZGCFG7m2Pl5FImyGyxlneP85yVaVAJhepB+gCkAWkzhLWhCLeBAmtW8dCpmhWq5rc1291D0BlSdYuGRIx1PNEUSz7/SOjPgriFpbHugj5sE/tIyW5+5UjyFXK48byRF4vDHJ2jorTINnKMqD42Dure5l9RJb2PNV2H6p0/k0LlkNFG2E0q7zAoqxtYfGjJR0CfqKV5x2Adia4mp1gHI7YBCC9fwJROn7GkydkmWF8+gtDXikxV7rVc2YHtMyzkGmAd+eFlAPhT+sHyA31djs9Wb7TwXCqPOTUr5gDklFnz9SA5nr8faO2rLTNJy1qbTiA7ysmLso65OXg1+iOIVmiQ2x/O6TGfAKgXNJCk2hl8/KF5zTsQ0J4g1v7XatvNeLq3cboeCbpm56xIJ0LaTgwVlpnkuXPQnfAAXY30wTwZ6g5Hq9J/BlOYSQQKi6EbpAa6BjpbNMsz9OxgRDl6cY+tw9BagM8iK/fuewykQsRaOWRmq0CNGLyqlYVxqa703THhCRUT5JpgLvoO/ffXoGGDHGxe5tY8GZCw55Fp3YC9dwH0BLUnp6fjk8Woip0ccftiWjaYANsYCzDN/dtJ6xjEqeC73Qz1SRMFnU=
before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.29/hugo_0.29_Linux-64bit.tar.gz
  - tar -xvzf hugo_0.29_Linux-64bit.tar.gz
  - cp hugo ~/bin/
  - pip install awscli --user `whoami`
  - aws configure set preview.cloudfront true
script:
  - make public
deploy:
  - provider: script
    script: make staging deploy
    skip_cleanup: true
    on:
      branch: staging
  - provider: script
    script: make production deploy
    skip_cleanup: true
    on:
      branch: master
