baseurl = "http://localhost/"
languageCode = "en-us"
title = "Pilosa"
theme = "sloth"

enableRobotsTXT = true

[params]
    company = "Pilosa"
    logo = "logo.svg"
    logo_white = "logo_white.svg"
    concepts = "concepts.svg"
    splash_home = "splash_home.svg"
    splash_home3 = "splash_home3.svg"
    animation_home_ourstory = "animation_home_ourstory.gif"
    badge = "badge.svg"
    info_security = "info_security.svg"
    hands = "hands.svg"
    splash_about = "splash_about.svg"
    splash_coc = "splash_coc.svg"
    press-release = "press-release.svg"
    splash_community = "splash_community.svg"
    pilosa_docs = "pilosa_docs.svg"
    splash_blog = "splash_blog.svg"
    slack = "slack.svg"
    github = "github.svg"
    stack_overflow = "stack_overflow.png"
    ce = "ce.svg"
    ee = "ee.svg"
    twitter = "twitter.svg"
    fb = "fb.svg"
    linkedin = "linkedin.svg"
    author_06 = "author_06.svg"
    author_01 = "author_01.svg"
    splash_404 = "splash_404.svg"
    title = "Pilosa"
    subtitle = "Beyond the cloud."

    tagline = "it's fast."
