baseurl = "https://www.pilosa.com/"
languageCode = "en-us"
title = "Pilosa"
theme = "sloth"

enableRobotsTXT = true
googleAnalytics = "UA-96186501-1"
ignoreFiles = []

[params]
    company = "Pilosa"
    logo = "logo.svg"
    logo_png = "logo.png"
    logo_small_png = "logo-small.png"
    logo_medium_png = "logo-medium.png"
    logo_stacked_png = "logo_stacked.png"
    logo_white = "logo_white.svg"
    concepts = "concepts.svg"
    splash_home = "splash_home.svg"
    splash_home3 = "splash_home3.svg"
    animation_home_ourstory = "animation_home_ourstory.gif"
    badge = "badge.svg"
    info_security = "info_security.svg"
    hands = "hands.svg"
    splash_about = "splash_about.svg"
    splash_coc = "splash_coc.svg"
    press-release = "press-release.svg"
    splash_community = "splash_community.svg"
    pilosa_docs = "pilosa_docs.svg"
    splash_blog = "splash_blog.svg"
    splash_careers = "splash_careers.svg"
    slack = "slack.svg"
    mail = "mail.svg"
    github = "github.svg"
    stack_overflow = "stack_overflow.png"
    ce = "ce.svg"
    ee = "ee.svg"
    twitter = "twitter.svg"
    fb = "fb.svg"
    linkedin = "linkedin.svg"
    author_06 = "author_06.svg"
    author_01 = "author_01.svg"
    splash_404 = "splash_404.svg"
    splash_use_cases = "splash_use_cases.png"
    splash_press = "splash_press.svg"
    community_sloth = "community_sloth.svg"
    speed_sloth = "speed_sloth.svg"
    resilience_sloth = "resilience_sloth.svg"
    drive_sloth = "drive_sloth.svg"
    covered = "covered.svg"
    fed = "fed.svg"
    fit = "fit.svg"
    flexible = "flexible.svg"
    inclusive = "inclusive.svg"
    learning_and_growing = "learning_and_growing.svg"
    title = "Pilosa"
    subtitle = "Beyond the cloud."
    twitter_url = "https://twitter.com/slothware"
    facebook_url = "https://www.facebook.com/pilosaco"
    linkedin_url = "https://linkedin.com/company/pilosa"
    description = "Pilosa is an open source, distributed bitmap index that dramatically accelerates queries across multiple, massive data sets."

[taxonomies]
    featured = "featured"
