baseurl = "http://localhost/"
languageCode = "en-us"
title = "Pilosa"
theme = "sloth"

#enableRobotsTXT = false

[params]
    company = "Pilosa"
    logo = "logo.svg"
    logo_white = "logo_white.svg"
    title = "Pilosa"
    subtitle = "Beyond the cloud."

    tagline = "it's fast."
