baseurl = "http://localhost/"
languageCode = "en-us"
title = "Pilosa"
theme = "sloth"

enableRobotsTXT = true

[params]
    company = "Pilosa"
    logo = "logo.svg"
    logo_white = "logo_white.svg"
    concepts = "concepts.svg"
    splash_home = "splash_home.svg"
    badge = "badge.svg"
    hands = "hands.svg"
    splash_about = "splash_about.svg"
    press-release = "press-release.svg"
    splash_community = "splash_community.svg"
    pilosa_docs = "pilosa_docs.svg"
    slack = "slack.svg"
    github = "github.svg"
    stack_overflow = "stack_overflow.png"
    ce = "ce.svg"
    ee = "ee.svg"
    twitter = "twitter.svg"
    fb = "fb.svg"
    linkedin = "linkedin.svg"
    title = "Pilosa"
    subtitle = "Beyond the cloud."

    tagline = "it's fast."
