baseurl = "https://www.pilosa.com/"
languageCode = "en-us"
title = "Pilosa"

enableRobotsTXT = true
googleAnalytics = "UA-96186501-1"
ignoreFiles = []

[params]
    version_major = "1"
    version_minor = "3"
    version_patch = "0"
    company = "Pilosa"
    logo = "logo.svg"
    logo_png = "logo.png"
    logo_small_png = "logo-small.png"
    logo_medium_png = "logo-medium.png"
    logo_stacked_png = "logo_stacked.png"
    logo_white_inverse = "logo_white_inverse.svg"
    concepts = "adenine.svg"
    splash_home = "splash_home.svg"
    splash_home3 = "splash_home3.svg"
    animation_home_ourstory = "animation_home_ourstory.gif"
    badge = "badge.svg"
    use_case_icon_info_security = "info_security.svg"
    use_case_icon_audience_segmentation = "audience-segmentation.svg"
    use_case_icon_bioinformatics = "bioinformatics.svg"
    use_case_icon_smart_cities = "smart-cities.svg"
    use_case_icon_star_schema = "star-schema.svg"
    hands = "hands.svg"
    splash_about = "splash_about.svg"
    splash_coc = "splash_coc.svg"
    press-release = "press-release.svg"
    splash_community = "splash_community.svg"
    pilosa_docs = "pilosa_docs.svg"
    splash_blog = "splash_blog.svg"
    splash_careers = "splash_careers.svg"
    slack = "slack.svg"
    mail = "mail.svg"
    github = "github.svg"
    stack_overflow = "stack_overflow.png"
    google_groups = "google-groups.png"
    ce = "ce.svg"
    le = "le.svg"
    ee = "ee.svg"
    twitter = "twitter.svg"
    fb = "fb.svg"
    linkedin = "linkedin.svg"
    author_01 = "author_01.svg"
    author_02 = "author_02.svg"
    author_03 = "author_03.svg"
    author_04 = "author_04.svg"
    author_05 = "author_05.svg"
    author_06 = "author_06.svg"
    author_07 = "author_07.svg"
    splash_404 = "splash_404.svg"
    splash_use_cases = "splash_use_cases.png"
    splash_press = "splash_press.svg"
    community_sloth = "community_sloth.svg"
    speed_sloth = "speed_sloth.svg"
    resilience_sloth = "resilience_sloth.svg"
    drive_sloth = "drive_sloth.svg"
    covered = "covered.svg"
    fed = "fed.svg"
    fit = "fit.svg"
    flexible = "flexible.svg"
    inclusive = "inclusive.svg"
    learning_and_growing = "learning_and_growing.svg"
    title = "Pilosa"
    subtitle = "Continuous Analysis on Really Big Data"
    twitter_url = "https://twitter.com/slothware"
    facebook_url = "https://www.facebook.com/pilosaco"
    linkedin_url = "https://linkedin.com/company/pilosa"
    github_url = "https://github.com/pilosa"
    description = "Pilosa is an open source, distributed bitmap index that dramatically accelerates continuous analysis across multiple, massive data sets."

[taxonomies]
    featured = "featured"
