baseurl = "http://localhost/"
languageCode = "en-us"
title = "Pilosa"
theme = "sloth"

enableRobotsTXT = true

[params]
    company = "Pilosa"
    logo = "logo.svg"
    logo_white = "logo_white.svg"
    concepts = "concepts.svg"
    splash_home = "splash_home.svg"
    hands = "hands.svg"
    splash_about = "splash_about.svg"
    press-release = "press-release.svg"
    ce = "ce.svg"
    ee = "ee.svg"
    title = "Pilosa"
    subtitle = "Beyond the cloud."

    tagline = "it's fast."
